networks:
  kepegawaian_default:
    external: true
    
services:
  laporan-kepegawaian:
    container_name: laporan-kepegawaian
    build: .
    ports:
      - "82:80"
    env_file:
      - .env
    networks:
      - kepegawaian_default