version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  colored:
    format: '%(asctime)s - %(name)s - %(levelname)-8s - %(message)s'
    datefmt: '%H:%M:%S'

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  # Console Handler
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

  # File Handler with rotate
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: "logs/app.log"
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf8
    mode: a

  # File Handler Error
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: "logs/app-error.log"
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8
    mode: a


loggers:
  # Logger for App
  cronjob:
    level: DEBUG
    handlers: [ file, console, error_file ]
    propagate: False

  # Logger for Scheduler
  schedule:
    level: WARNING
    handler: [ file, console ]

root:
  level: INFO
  handlers: [ file, console, error_file ]